DROP TABLE IF EXISTS text;
DROP TABLE IF EXISTS url;


CREATE TABLE text (
       id INTEGER PRIMARY KEY AUTOINCREMENT,
       pdf_file TEXT NOT NULL,
       text TEXT UNIQUE NOT NULL
);


CREATE TABLE url (
       id INTEGER PRIMARY KEY AUTOINCREMENT
       text_id INTEGER NOT NULL,
       link TEXT UNIQUE NOT NULL,
       created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
       FOREIGN KEY (text_id) REFERENCES text (id)
);
